config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registration

  resources :visitors

  resources :barista

  resources :buyers

  resources :articles

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    root :to => "rails_admin/main#dashboard"
  end

  root to: "home#index"

  get 'gallery', to: 'home#gallery', as: 'gallery'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'iobc', to: 'home#iobc', as: 'iobc'
  get 'workshops', to: 'home#workshops', as: 'workshops'
  get 'exhibitions', to: 'home#exhibitions', as: 'exhibitions'
  get 'auctions', to: 'home#auctions', as: 'auctions'
  get 'download', to: 'home#download_map', as: 'download'
  get 'event', to: 'home#event', as: 'event'
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  before_save :send_confirmation, :if => :new_record?

  private
    def send_confirmation
      	Contact.send_to_us(self).deliver if Contact.send_visitor_confirmation(self).deliver
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if verify_recaptcha
        if @visitor.save
          # format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
          format.html { redirect_to contact_path, notice: 'Message send successfully.' }
          format.json { render :show, status: :created, location: @visitor }
        else
          format.html { render :new }
          format.json { render json: @visitor.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :email, :subject, :message)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.haml
= form_for(@visitor) do |f|
  - if @visitor.errors.any?
    #error_explanation
      %h2
        = pluralize(@visitor.errors.count, "error")
        prohibited this visitor from being saved:
      %ul
        - @visitor.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :subject
    %br/
    = f.text_field :subject
  .field
    = f.label :message
    %br/
    = f.text_area :message
  .actions
    = f.submit

app/views/visitors/edit.html.haml
%h1 Editing visitor
= render 'form'
= link_to 'Show', @visitor
|
\#{link_to 'Back', visitors_path}

app/views/visitors/index.html.haml
%h1 Listing visitors
%table
  %thead
    %tr
      %th Name
      %th Email
      %th Subject
      %th Message
      %th{:colspan => "3"}
  %tbody
    - @visitors.each do |visitor|
      %tr
        %td= visitor.name
        %td= visitor.email
        %td= visitor.subject
        %td= visitor.message
        %td= link_to 'Show', visitor
        %td= link_to 'Edit', edit_visitor_path(visitor)
        %td= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Visitor', new_visitor_path

app/views/visitors/new.html.haml
.banner
  .wrap
    %h2 CONTACT
    .clear
.main
  .project-wrapper
    .wrap
      .contact
        .cont.span_2_of_contact
          %h5.leave Send Us A Message
          .clear
          = form_for(@visitor) do |f|
            .contact-to.clearfix
              = f.text_field :name, class: "text", placeholder: "Name...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Name...';}", required: true
              .clear
              = f.email_field :email, class: "text", placeholder: "Email...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Email...';}", required: true
              .clear
              = f.text_field :subject, class: "text", placeholder: "Subject...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Subject...';}", required: true
              .clear
              = f.text_area :message, class: "text", placeholder: "Message...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Message...';}", required: true
              .clear
              = recaptcha_tags
              .clear
              = f.submit :register, value: "Send", class: 'submit'
        .lsidebar.span_1_of_about
          %h5.leave Contact Info
          .clear
          .contact-list
            %ul
              %li
                %img{:alt => "", :src => "/assets/address.png"}/
                %p MG COFFEE ACADEMY, Setrasari Mall kav C2 no 31, Jl. Prof. Dr. Ir. Soetami, Bandung - West Java, Indonesia
                .clear
              %li
                %img{:alt => "", :src => "/assets/phone.png"}/
                %p Phone/WA : +6282226524674 | LINE : mgcoffeeacademy | BB : 7F76A3D2
                .clear
              %li
                %img{:alt => "", :src => "/assets/msg.png"}/
                %p
                  Email:
                  %span.yellow1
                    %a{:href => "#"} info(at)BandungCoffeeFestival.com
                .clear
        .clear

app/views/visitors/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @visitor.name
%p
  %strong Email:
  = @visitor.email
%p
  %strong Subject:
  = @visitor.subject
%p
  %strong Message:
  = @visitor.message
= link_to 'Edit', edit_visitor_path(@visitor)
|
\#{link_to 'Back', visitors_path}