config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registration

  resources :visitors

  resources :barista

  resources :buyers

  resources :articles

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    root :to => "rails_admin/main#dashboard"
  end

  root to: "home#index"

  get 'gallery', to: 'home#gallery', as: 'gallery'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'iobc', to: 'home#iobc', as: 'iobc'
  get 'workshops', to: 'home#workshops', as: 'workshops'
  get 'exhibitions', to: 'home#exhibitions', as: 'exhibitions'
  get 'auctions', to: 'home#auctions', as: 'auctions'
  get 'download', to: 'home#download_map', as: 'download'
  get 'event', to: 'home#event', as: 'event'
end

app/views/shared/_footer.html.haml
= render 'shared/partner'

.footer
  .footer-top
    .wrap
      .section.group
        .col_1_of_3.span_1_of_3
          %h3 About Us
          %p The Bandung Coffee Festival promises to be an unmissable event for discerning coffee lovers and those working in the coffee scene. Buyers and sellers are more than welcome. From harvesting to brewing and artisan catering to equipment, this show will showcase every aspect of the coffee world and all the enjoyment that goes with it. The festival will feature over 25 coffee estates at Kabupaten Bandung District coffee, coffee shops, long business hours, coffee competition, coffee auctions, and gourmet food stalls, tastings and demonstrations from baristas, interactive workshops, and many more.
          = link_to "Learn more", about_path, class: 'button btn1 btn-8 btn-8b'
        .col_1_of_3.span_1_of_3
          = link_to "Tweets by @BdgCoffeeFest", "https://twitter.com/BdgCoffeeFest", class: "twitter-timeline", :"data-dnt" => true, :"data-widget-id" => "528066834944098304"
        .col_1_of_3.span_1_of_3
          %h3 Contact info
          .footer-list
            %ul
              %li
                %img{:alt => "", :src => "/assets/address.png"}/
                %p MG COFFEE ACADEMY, Setrasari Mall kav C2 no 31, Jl. Prof. Dr. Ir. Soetami, Bandung - West Java, Indonesia
                .clear
              %li
                %img{:alt => "", :src => "/assets/phone.png"}/
                %p Phone/WA : +6282226524674 | LINE : mgcoffeeacademy | BB : 7F76A3D2
                .clear
              %li
                %img{:alt => "", :src => "/assets/msg.png"}/
                %p
                  Email:
                  %span.yellow
                    %a{:href => "#"} info(at)BandungCoffeeFestival.com
                .clear
          .follow
            %h4 Follow Us
            %p The Bandung Coffee Festival celebrates West Java?s bustling and vibrant coffee scene. Its is a show dedicated to celebrating all that's new and exciting on the Coffee landscape.
            .search

        .clear
  .footer-bottom
    .wrap
      .copy
        %p.copy
          © 2014 Copyright by
          %a{:href => "#", :target => "_blank"} Bandung Coffee Festival
      .footer-nav
        %ul
          %li= link_to "Home", root_path
          %li= link_to "Events", event_path
          %li= link_to "About Us", about_path
          %li= link_to "Gallery", gallery_path
          %li= link_to "Contact", contact_path
          %li= link_to "FAQ", faq_path
      .clear

app/views/shared/_header.html.haml
.header
  .wrap
    .logo
      = link_to root_path do
        = image_tag "logo.png", alt: 'Bandung Coffee Festival'
    .cssmenu
      %ul
        %li= link_to "Home", root_path
        %li
          = link_to "Events", event_path
          %ul
            %li.sub= link_to 'Exhibition', exhibitions_path
            %li.sub= link_to 'Coffee Competition & Auction', auctions_path
            %li.sub= link_to 'IOBC', iobc_path
            %li.sub= link_to 'Workshop', workshops_path
        %li
          = link_to "Registrations", "#"
          %ul
            %li.sub= link_to "Buyers", new_buyer_path
            %li.sub= link_to "Barista Championship", new_baristum_path
        %li= link_to "About Us", about_path
        %li= link_to "Gallery", gallery_path
        %li= link_to "Contact", contact_path
        %li= link_to "FAQ", faq_path
    .clear

app/views/shared/_notification.html.haml
- if notice || alert
  %div{:class => "alert alert-#{notice ? 'success' : 'danger'} alert-dismissable", :style => "margin-top: 58px;"}
    - if notice
      %i.fa.fa-check
    - else
      %i.fa.fa-ban
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
    %b
      = notice ? notice : alert
.clear

app/views/shared/_partner.html.haml
.content-bottom
  %h2
    %span Partners
  %p Sponsors and Media Partnership by
  %ul#flexiselDemo3
    %li
      %img{:src => "/assets/client1.jpg"}
    %li
      %img{:src => "/assets/client2.jpg"}
    %li
      %img{:src => "/assets/client3.jpg"}
    %li
      %img{:src => "/assets/client4.jpg"}
    %li
      %img{:src => "/assets/client5.jpg"}
    %li
      %img{:src => "/assets/client6.jpg"}
    %li
      %img{:src => "/assets/client7.jpg"}
    %li
      %img{:src => "/assets/client8.jpg"}

    %link{:href => "/assets/colorbox.css", :rel => "stylesheet"}/
    %script{:src => "/assets/jquery.imagesloaded.js"}
    %script{:src => "/assets/jquery.colorbox-min.js"}
    %script{:src => "/assets/jquery.wookmark.js"}
    :javascript
      (function ($){
        $('#tiles').imagesLoaded(function() {
          var options = {
            autoResize: true,
            container: $('#main1'),
            offset: 2,
            itemWidth:200
          };
          var handler = $('#tiles li');
          handler.wookmark(options);
          $('a', handler).colorbox({
            rel: 'lightbox'
          });
        });
      })(jQuery);