config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registration

  resources :visitors

  resources :barista

  resources :buyers

  resources :articles

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    root :to => "rails_admin/main#dashboard"
  end

  root to: "home#index"

  get 'gallery', to: 'home#gallery', as: 'gallery'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'iobc', to: 'home#iobc', as: 'iobc'
  get 'workshops', to: 'home#workshops', as: 'workshops'
  get 'exhibitions', to: 'home#exhibitions', as: 'exhibitions'
  get 'auctions', to: 'home#auctions', as: 'auctions'
  get 'download', to: 'home#download_map', as: 'download'
  get 'event', to: 'home#event', as: 'event'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;end

  def about;end

  def contact
    redirect_to new_visitor_path
  end

  def faq;end

  def iobc;end

  def workshops;end

  def exhibitions;end

  def auctions;end

  def download_map
    send_file Rails.root.join('app/assets/images/layout.jpg'), :type => 'image/jpg', filename: 'map.jpg'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_gallery_all.html.haml
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => " "}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 1.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 2.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.iobc.mix_all{"data-cat" => "iobc", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 6.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.iobc.mix_all{"data-cat" => "iobc", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 4.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.iobc.mix_all{"data-cat" => "iobc", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 5.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 3.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 7.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 8.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 14.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 10.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 11.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear
.portfolio.bcf.mix_all{"data-cat" => "bcf", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/bandung_coffe 12.jpg"}/
    .links
      %h4
        %a{:href => ""} Bandung Coffee Festival
      .clear

app/views/home/_presscon_gallery.html.haml
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => " "}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6299.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6301.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.iobc-presscon.mix_all{"data-cat" => "iobc-presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6330.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.iobc-presscon.mix_all{"data-cat" => "iobc-presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6335.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.iobc-presscon.mix_all{"data-cat" => "iobc-presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6365.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6380.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6394.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6396.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6420.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6428.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6435.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6441.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6449.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6465.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6469.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6484.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6498.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6509.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6520.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6523.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6527.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6541.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6543.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6546.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6550.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6553.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6560.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6563.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6578.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6581.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6597.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6623.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear
.portfolio.presscon.mix_all{"data-cat" => "presscon", :style => "  display: inline-block; opacity: 1;"}
  .portfolio-wrapper
    %a{:href => "#"}
      %img{:alt => "bandungcoffee", :src => "/assets/presscon/IMG_6631.JPG"}/
    .links
      %h4
        %a{:href => ""} Presscon
      .clear

app/views/home/about.html.haml
.banner
  .wrap
    %h2 About Us
    .clear
.main
  .project-wrapper
    .wrap
      .section.group
        .cont.span_2_of_about
          %p
            The Bandung Coffee Festival is the industry’s top-performing show, consistently providing visitors with relevant information to hone their coffee business skills and up their bottom line, including coffee farmers and manufacturers and service companies the face to face opportunities to build their businesses. This is an annual event to celebrates West Java’s bustling and vibrant coffee scene. Its is a show dedicated to celebrating all that's new and exciting on the Coffee landscape.
          %br/
          %br/
          %p
            The Bandung Coffee Festival promises to be an unmissable event for discerning coffee lovers and those working in the coffee scene. Buyers and sellers are more than welcome.
          %br/
          %br/
          %h5 The event will be held :
          %br
          %h5 BANDUNG COFFEE FESTIVAL 2014
          %h5 Date : 5-6 November 21040
          %h5 Venue : Gedung Moh. Toha, Kompleks Pemda Kabupaten Bandung, Soreang, West Java
          %br/
          %br/
          %p
            From harvesting to brewing and artisan catering to equipment, this show will showcase every aspect of the coffee world and all the enjoyment that goes with it. The festival will feature over 25 coffee estates at Kabupaten Bandung District coffee, coffee shops, long business hours, coffee competition, coffee auctions, and gourmet food stalls, tastings and demonstrations from baristas, interactive workshops, and many more.
          %br/
          %br/
          %p
            The Bandung Coffee Festival is a collaboration of Department fo Agriculture, Plantation and Forestry Kabupaten Bandung and #{ link_to "Morning Glory Coffee Academy", "http://mgcoffeeacademy.com/"}
          %br/
          %br/
          %center
            %img{:src => "../assets/logo-mg.png"}/
          %p
            #{ link_to "Morning Glory Coffee Academy", "http://mgcoffeeacademy.com/"} is a well-known coffee education center in Indonesia. All of our courses have been accredited by Specialty Coffee Association of Europe (SCAE). The Professional-Based Certificates will allow participants to demonstrate specified knowledge, skill competency and networking in the coffee industries. MG Coffee Academy develops a super fun learning process. We believe on practical aspects. You will be brought to the next level of attitude, skill and knowledge. More Information check on our website #{ link_to "here", "http://mgcoffeeacademy.com/"}.
        .clear

app/views/home/auctions.html.haml
.banner
  .wrap
    %h2 COFFEE COMPETITION & AUCTION
  .clear
.main
  .project-wrapper
    .wrap
      .section.group
        .cont.span_2_of_about
          %br
          %br
          %p
            In this event, there will be more than 20 profiles of coffee ready for cupping at the coffee competition.
          %p
            These coffee were produce at Kabupaten Bandung area's Estates which famous of its unique fruity flavour. We will perform a transparent auctions who will benefit the farmers. Most of the coffee auctions are for next years harvesting but a few samples are ready for you during the event. Micro auction is applied.
          %br
          %br
          %p
            The coffee competition and business hour for auction is on the first day of the event, 5 November 2014, starts at 10.00-12.00AM and continue at 14.00-16.00.
          %br
          %br
          %p
            for register yourself as a buyer,
            = link_to new_buyer_path do
              = image_tag "click.png", class: 'klik'
          %br
          %br
            \----
          %br
          %p
            Business hours is when the coffee buyers all over the world taste and bid for coffee. The hours contain coffee competition from many estates and auction session. Newest world standard of coffee tasting will be applied. Our business hours will provide you the opportunity to join the coffee auctions.
          %p
          %br
            Please register as a buyer :
            = link_to new_baristum_path do
              = image_tag "click.png", class: 'klik'
            or email us :
          %strong
            %i= mail_to "info@bandungcoffeefestival.com"
          %br
          %br
          %p
            If you are an international buyer, our VIP services will provide you a free airport transfers (From Bandung Hussein Sastranegara Int Airport), daily suttles from hotel to venue and assistance for hotels and many interesting places around Bandung area.
          %br
          %br
        .clear

app/views/home/contact.html.haml
.banner
  .wrap
    %h2 CONTACT
    .clear
.main
  .project-wrapper
    .wrap
      .cont.span_2_of_contact
        .map
          %iframe{:frameborder => "0", :height => "400", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://maps.google.co.in/maps?f=q&source=s_q&hl=en&geocode=&q=Lighthouse+Point,+FL,+United+States&aq=4&oq=light&sll=26.275636,-80.087265&sspn=0.04941,0.104628&ie=UTF8&hq=&hnear=Lighthouse+Point,+Broward,+Florida,+United+States&t=m&z=14&ll=26.275636,-80.087265&output=embed", :width => "100%"}
          %br/
          %small
            %a{:href => "https://maps.google.co.in/maps?f=q&source=embed&hl=en&geocode=&q=Lighthouse+Point,+FL,+United+States&aq=4&oq=light&sll=26.275636,-80.087265&sspn=0.04941,0.104628&ie=UTF8&hq=&hnear=Lighthouse+Point,+Broward,+Florida,+United+States&t=m&z=14&ll=26.275636,-80.087265", :style => "color:#666;text-align:left;font-size:12px"}
      .lsidebar.span_1_of_about
        %img{:alt => "", :src => "/assets/layout.jpg"}/
        %br/
        %br/
    .wrap
      .contact
        .cont.span_2_of_contact
          %h5.leave Send Us A Message
          .clear
          = form_for(@buyer) do |f|
            .contact-to.clearfix
              = f.text_field :name, class: "text", placeholder: "Name...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Name...';}", required: true
              .clear
              = f.email_field :email, class: "text", placeholder: "Email...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Email...';}", required: true
              .clear
              = f.text_field :company, class: "text", placeholder: "Company...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Company...';}", required: true
              .clear
              = f.text_area :company_address, class: "text", placeholder: "Address...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Address...';}", required: true
              .clear
              = f.phone_field :telp, class: "text", placeholder: "Phone Number...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Phone Number...';}", required: true
              .clear
            = f.submit :register, value: "Register", class: 'submit'
        .lsidebar.span_1_of_about
          %h5.leave Contact Info
          .clear
          .contact-list
            %ul
              %li
                %img{:alt => "", :src => "/assets/address.png"}/
                %p MG COFFEE ACADEMY, Setrasari Mall kav C2 no 31, Jl. Prof. Dr. Ir. Soetami, Bandung - West Java, Indonesia
                .clear
              %li
                %img{:alt => "", :src => "/assets/phone.png"}/
                %p Phone/WA : +6282226524674 | LINE : mgcoffeeacademy | BB : 7F76A3D2
                .clear
              %li
                %img{:alt => "", :src => "/assets/msg.png"}/
                %p
                  Email:
                  %span.yellow1
                    %a{:href => "#"} info(at)BandungCoffeeFestival.com
                .clear
        .clear

app/views/home/exhibitions.html.haml
.banner
  .wrap
    %h2 FLOOR PLAN
    .clear
.main
  .project-wrapper
    .wrap
      .section.group
        .cont.span_2_of_about
          %img.layout{:alt => "Layout", :src => "assets/layout-mini.png"}/
          %img.logosm{:alt => "Layout", :src => "assets/logo-date-sm.png"}/
          = link_to download_path do
            = image_tag "downloadfloorplan.png", class: 'download'
        .clear

app/views/home/index.html.haml
.index-banner
  .wmuSlider.example1
    .wmuSliderWrapper
      %article{:style => "position: absolute; width: 100%; opacity: 0;"}
        .banner-wrap
          .slider-left
            %h3 BANDUNG
            %h4 COFFEE FESTIVAL
            %p.top The Bandung Coffee Festival celebrates West Java’s bustling and vibrant coffee scene.
            %p.middle Mark your date : 5-6 November 2104, Gedung Moh. Toha, Kompleks Pemda Kabupaten Bandung, Soreang, West Java
            %p.bottom all that's new and exciting on the Coffee landscape
            = link_to "Register Buyer", new_buyer_path, class: "btn btn-8 btn-8b"
            = link_to "Register Barista Competition", new_baristum_path, class: "btn btn-8 btn-8b"
          .slider-right
            %img{:src => "/assets/banner-left.png"}/
          .clear
      - (1..4).each do |article|
        %article{:style => "position: relative; width: 100%; opacity: 1;"}
          .banner-wrap
            .slider-right
              %img{:src => "/assets/banner-left.png"}/
            .slider-left
              %h3 BANDUNG
              %h4 COFFEE FESTIVAL
              %p.top The Bandung Coffee Festival celebrates West Java’s bustling and vibrant coffee scene.
              %p.middle Mark your date : 5-6 November 2104, Gedung Moh. Toha, Kompleks Pemda Kabupaten Bandung, Soreang, West Java
              %p.bottom all that's new and exciting on the Coffee landscape
              = link_to "Register Buyer", new_buyer_path, class: "btn btn-8 btn-8b"
              = link_to "Register Barista Competition", new_baristum_path, class: "btn btn-8 btn-8b"
            .clear
      %a.wmuSliderPrev Previous
      %a.wmuSliderNext Next
      %ul.wmuSliderPagination
        %li
          %a{:href => "#"} 0
        %li
          %a{:href => "#"} 1
        %li
          %a.wmuActive{:href => "#"} 2
        %li
          %a{:href => "#"} 3
        %li
          %a{:href => "#"} 4
%br
%br
.main
  .content-top
    .wrap
      %h3 Welcome to the first ever Bandung Coffee Festival
      %h5 The Bandung Coffee Festival promises to be an unmissable event for discerning coffee lovers and those working in the coffee scene. Buyers and sellers are more than welcome.
      .section.group
        .col_1_of_4.span_1_of_4
          .grid1
            = link_to about_path do
              %img{alt: "", src: "assets/icon1.png"}
              %h4 About BCF 2014
          .desc
            %p The First Ever Coffee Festival in Bandung. Lets join!
        .col_1_of_4.span_1_of_4
          .grid1
            = link_to event_path  do
              %img{alt: "", src: "assets/icon2.png"}
              %h4 Event
          .desc
            %p Show photo of yours & Share the moments of happiness
        .col_1_of_4.span_1_of_4
          .grid1
            = link_to new_buyer_path do
              %img{alt: "", src: "assets/icon3.png"}
              %h4 Register Buyer
          .desc
            %p Register here for All Buyers for Free!
        .col_1_of_4.span_1_of_4
          .grid1
            = link_to new_baristum_path do
              %img{alt: "", src: "assets/icon4.png"}
              %h4 Register Barista
          .desc
            %p Register to Barista Competition here
        .clear