config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :skip => :registration

  resources :visitors

  resources :barista

  resources :buyers

  resources :articles

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :admin do
    root :to => "rails_admin/main#dashboard"
  end

  root to: "home#index"

  get 'gallery', to: 'home#gallery', as: 'gallery'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'
  get 'faq', to: 'home#faq', as: 'faq'
  get 'iobc', to: 'home#iobc', as: 'iobc'
  get 'workshops', to: 'home#workshops', as: 'workshops'
  get 'exhibitions', to: 'home#exhibitions', as: 'exhibitions'
  get 'auctions', to: 'home#auctions', as: 'auctions'
  get 'download', to: 'home#download_map', as: 'download'
  get 'event', to: 'home#event', as: 'event'
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  validates :email, :presence => true, :uniqueness => true

  before_save :send_confirmation, :if => :new_record?

  private
    def send_confirmation
      Contact.buyer_send_to_us(self).deliver if Contact.send_buyer_confirmation(self).deliver
    end
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if verify_recaptcha
        if @buyer.save
          # format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
          # format.json { render :show, status: :created, location: @buyer }
          format.html { redirect_to root_path, notice: 'Buyer was successfully created.' }
        else
          format.html { render :new }
          # format.json { render json: @buyer.errors, status: :unprocessable_entity }
          # format.html { redirect_to root_path, alert: @buyer.error }
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name, :gender, :company, :job_title, :company_address, :city, :postal_code, :country, :telp, :fax, :mobile, :email, :website)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.html.haml
= form_for(@buyer) do |f|
  - if @buyer.errors.any?
    #error_explanation
      %h2
        = pluralize(@buyer.errors.count, "error")
        prohibited this buyer from being saved:
      %ul
        - @buyer.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :gender
    %br/
    = f.text_field :gender
  .field
    = f.label :company
    %br/
    = f.text_field :company
  .field
    = f.label :job_title
    %br/
    = f.text_field :job_title
  .field
    = f.label :company_address
    %br/
    = f.text_area :company_address
  .field
    = f.label :city
    %br/
    = f.text_field :city
  .field
    = f.label :postal_code
    %br/
    = f.text_field :postal_code
  .field
    = f.label :country
    %br/
    = f.text_field :country
  .field
    = f.label :telp
    %br/
    = f.text_field :telp
  .field
    = f.label :fax
    %br/
    = f.text_field :fax
  .field
    = f.label :mobile
    %br/
    = f.text_field :mobile
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :website
    %br/
    = f.text_field :website
  .actions
    = f.submit

app/views/buyers/edit.html.haml
%h1 Editing buyer
= render 'form'
= link_to 'Show', @buyer
|
\#{link_to 'Back', buyers_path}

app/views/buyers/index.html.haml
%h1 Listing buyers
%table
  %thead
    %tr
      %th Name
      %th Gender
      %th Company
      %th Job title
      %th Company address
      %th City
      %th Postal code
      %th Country
      %th Telp
      %th Fax
      %th Mobile
      %th Email
      %th Website
      %th{:colspan => "3"}
  %tbody
    - @buyers.each do |buyer|
      %tr
        %td= buyer.name
        %td= buyer.gender
        %td= buyer.company
        %td= buyer.job_title
        %td= buyer.company_address
        %td= buyer.city
        %td= buyer.postal_code
        %td= buyer.country
        %td= buyer.telp
        %td= buyer.fax
        %td= buyer.mobile
        %td= buyer.email
        %td= buyer.website
        %td= link_to 'Show', buyer
        %td= link_to 'Edit', edit_buyer_path(buyer)
        %td= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Buyer', new_buyer_path

app/views/buyers/new.html.haml
.banner
  .wrap
    %h2 REGISTER BUYER
    .clear
.main
  .project-wrapper
    .wrap
      %h5.leave Register as Buyer
      %br
      .contact
        .cont.span_2_of_contact
          = form_for(@buyer) do |f|
            .contact-to.clearfix
              = f.text_field :name, class: "text", placeholder: "Name...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Name...';}", required: true
              .clear
              = f.select :gender, options_for_select([["Male", "Male"], ["Female", "Female"]]), {prompt: "-- Choose Gender --", selected: "", class: 'text'}
              .clear
              = f.text_field :company, class: "text", placeholder: "Company...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Company...';}", required: true
              .clear
              = f.text_field :job_title, class: "text", placeholder: "Job Title...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Job Title...';}", required: true
              .clear
              = f.text_area :company_address, class: "text", placeholder: "Address...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Address...';}", required: true
              .clear
              = f.text_field :city, class: "text", placeholder: "City...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'City...';}", required: true
              .clear
              = f.text_field :postal_code, class: "text", placeholder: "Postal code...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Postal Code...';}", required: true
              .clear
              = f.text_field :country, class: "text", placeholder: "Country...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Country...';}", required: true
              .clear
              = f.text_field :telp, class: "text", placeholder: "Phone...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Phone...';}", required: true
              .clear
              = f.phone_field :fax, class: "text", placeholder: "Fax...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Fax...';}", required: true
              .clear
              = f.phone_field :mobile, class: "text", placeholder: "Mobile...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Mobile...';}", required: true
              .clear
              = f.email_field :email, class: "text", placeholder: "Email...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Email...';}", required: true
              .clear
              = f.phone_field :website, class: "text", placeholder: "Website...", onfocus: "this.value = '';", onblur: "if (this.value == '') {this.value = 'Website...';}", required: true
              .clear
              = recaptcha_tags
              .clear
            = f.submit :register, value: "Register", class: 'submit'
        .lsidebar.span_1_of_about
          %h5.leave Contact Info
          .clear
          .contact-list
            %ul
              %li
                %img{:alt => "", :src => "/assets/address.png"}/
                %p MG COFFEE ACADEMY, Setrasari Mall kav C2 no 31, Jl. Prof. Dr. Ir. Soetami, Bandung - West Java, Indonesia
                .clear
              %li
                %img{:alt => "", :src => "/assets/phone.png"}/
                %p Phone/WA : +6282226524674 | LINE : mgcoffeeacademy | BB : 7F76A3D2
                .clear
              %li
                %img{:alt => "", :src => "/assets/msg.png"}/
                %p
                  Email:
                  %span.yellow1
                    %a{:href => "#"} info(at)BandungCoffeeFestival.com
                .clear
        .clear

app/views/buyers/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @buyer.name
%p
  %strong Gender:
  = @buyer.gender
%p
  %strong Company:
  = @buyer.company
%p
  %strong Job title:
  = @buyer.job_title
%p
  %strong Company address:
  = @buyer.company_address
%p
  %strong City:
  = @buyer.city
%p
  %strong Postal code:
  = @buyer.postal_code
%p
  %strong Country:
  = @buyer.country
%p
  %strong Telp:
  = @buyer.telp
%p
  %strong Fax:
  = @buyer.fax
%p
  %strong Mobile:
  = @buyer.mobile
%p
  %strong Email:
  = @buyer.email
%p
  %strong Website:
  = @buyer.website
= link_to 'Edit', edit_buyer_path(@buyer)
|
\#{link_to 'Back', buyers_path}